defaults: &defaults
  #微信token
  weixin_token: "weiyi"
  #为true则需要验证
  token_validate: true
  

development:
  weixin_blind: false
  <<: *defaults
test:
  weixin_blind: false
  <<: *defaults

production:
  weixin_blind: true
  <<: *defaults