defaults: &defaults
  #微信token
  weixin_token: "weiyi"
  #公司网站域名
  web_host: weiyizixun.com
  admin_user: admin@admin.com

development:
  weixin_blind: false
  <<: *defaults
test:
  weixin_blind: false
  <<: *defaults

production:
  weixin_blind: true
  <<: *defaults