defaults: &defaults
  #微信token
  weixin_token: "weiyi"
  #公司网站域名
  web_host: weiyizixun.com
  admin_user: noreply@weiyizixun.com
  #备案号
  record_code: "粤ICP备13072833-1"

development:
  weixin_blind: false
  <<: *defaults
test:
  weixin_blind: false
  <<: *defaults

production:
  weixin_blind: true
  <<: *defaults