defaults: &defaults
  #微信token
  weixin_token: "weiyi"
  

development:
  weixin_blind: false
  <<: *defaults
test:
  weixin_blind: false
  <<: *defaults

production:
  weixin_blind: true
  <<: *defaults