defaults: &defaults
  #微信token
  weixin_token: "weiyi"
  #为true则需要验证
  token_validate: false
  
  #公司网站域名
  web_host: weiyizixun.com

development:
  weixin_blind: false
  <<: *defaults
test:
  weixin_blind: false
  <<: *defaults

production:
  weixin_blind: true
  <<: *defaults